services:
  backend:
    build: ./be
    ports:
      - "8000:8000"
    volumes:
      - ./be:/app
    environment:
      - ARTIC_API_BASE_URL=https://api.artic.edu/api/v1
      - DATABASE_URL=sqlite:///./travel.db

  frontend:
    build: ./fe
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
